### PR TITLE
Remove unneeded provisioner blocks

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

Remove some now-unnecessary provisioner blocks from the Terraform code.

## 💭 Motivation and Context

Recent versions of Terraform give a deprecation warning for these provisioner blocks because they reference attributes from outside the associated resource.  In the future this will be disallowed, and only references to `self`, `count.index`, or `each.key` will be allowed in provisioner blocks.

I did some testing, and the provisioner blocks seem unnecessary now anyway, so I removed them.

## 🧪 Testing

I did a `terraform deploy` followed by a `terraform destroy` to verify that everything operated as expected without the provisioners. 

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Less is more 🚐

**Comment by jsf9k** [comment]
Assuming these changes are correct, that means we can get rid of a lot of similar provisioner blocks in [cisagov/cyhy_amis](https://github.com/cisagov/cyhy_amis), for example.

**Review by mcdonnnj — APPROVED** [review]
Slimming down! 🏋️‍♀️Nice work.

**Review by felddy — COMMENTED** [review]
Looks good!  🧞

**Pull request merged**
