### PR TITLE
Incorporate upstream changes from cisagov/skeleton-generic

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

Pull in upstream changes from [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic).

## 💭 Motivation and Context

I have some changes to make to this repository, so it makes sense to first bring it up to date with the skeleton it is based on.

## 🧪 Testing

I ensured that the GitHub Actions all execute successfully.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jsf9k** [comment]
This project should really be broken up into separate Packer and Terraform projects, but since this code is on its way out (in favor the new GoPhish code for PCA), I won't bother.

**Review by dav3r — APPROVED** [review]
Onward and upward! 🚀

**Review by mcdonnnj — APPROVED** [review]
Lookin' good to me. 🚀👍

**Review by felddy — APPROVED** [review]
Upstream looking good.   Bring it on!

**Pull request merged**
