### PR TITLE
Add Lineage configuration.

### PR DESCRIPTION
**Pull request by felddy**
# 

## 🗣 Description

Add Lineage configuration to enable automatic PRs from upstream. 

:eyes: Please verify that the correct upstream repo was selected.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
🥙

**Review by jsf9k — APPROVED** [review]
It took a little effort, but this is in good shape now.

This is ancient stuff from _just_ after the flood.  No single skeleton really fits, since the packer and terraform code are both in here.  Fortunately this code can be retired soon.

**Review by dav3r — APPROVED** [review]
Thanks for cleaning this up.  I was just going to let it die on the vine... ☠️

**Comment by felddy** [comment]
I feel like there should be a joke here... but it'd be so dark...  Nice work @jsf9k

**Pull request merged**
