### PR TITLE
Fix terraform-docs Installation URL in build Workflow

### PR DESCRIPTION
**Pull request by mcdonnnj**
# 

## 🗣 Description

This PR fixes the URL for installation of `terraform-docs` in the `build` workflow.

## 💭 Motivation and Context

I saw [apb](https://github.com/cisagov/action-apb) triggered builds failing for this project, and realized that because the [lineage](https://github.com/cisagov/action-lineage) configuration points to [cisagov/skeleton-generic](https://github.com/cisagov/skeleton-generic) it did not get the changes in https://github.com/cisagov/skeleton-tf-module/pull/33

## 🧪 Testing

Automated tests pass once more.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Thanks for fixing this @mcdonnnj.  FWIW, the PCA folks appear to be draining off the existing PCA teamservers that use this repo.  We should be able to archive this repo in the not-too-distant future.

Do lineage and apb ignore archived repos?  I hope so.

**Comment by mcdonnnj** [comment]
> 
> 
> Thanks for fixing this @mcdonnnj. FWIW, the PCA folks appear to be draining off the existing PCA teamservers that use this repo. We should be able to archive this repo in the not-too-distant future.
> 
> Do lineage and apb ignore archived repos? I hope so.

I just checked the search parameters for both and they include `archived: false`.

**Review by dav3r — APPROVED** [review]
image

**Review by hillaryj — APPROVED** [review]
Should the lineage configuration get updated to the tf skeleton?

**Comment by mcdonnnj** [comment]
> 
> 
> Should the lineage configuration get updated to the tf skeleton?

This is one of those older repos that's kind of a mashup of components. Since it's being phased out I don't think it's worth the effort of switching skeletons, but I'm open to it if we want to go that route.

**Comment by jsf9k** [comment]
> Should the lineage configuration get updated to the tf skeleton?

This repo predates the skeletons, and it combines Terraform and Ansible code.  The real solution would be to split it into several repos that each use the appropriate skeleton.

This way of doing PCAs is being phased out, after which this repo will be mothballed.  I don't think it is worth the effort to fully bring it into the light.

**Pull request merged**
